universal_binaries:
- replace: true
builds:
- env:
  - CGO_ENABLED=0
  main: ./pkg/cmd
  goos:
  - linux
  - darwin
  - windows
  - freebsd
  goarch:
  - amd64
  - arm64
  ignore:
    - goos: freebsd
      goarch: arm64
    - goos: windows
      goarch: arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w -X github.com/kong/chart-migrate/pkg/cmd.VERSION={{ .Tag }} -X github.com/kong/chart-migrate/pkg/cmd.COMMIT={{ .ShortCommit }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
archives:
- wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
